name: ch_kids
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.9
  cloud_firestore: ^4.15.5
  firebase_storage: ^11.6.5
  firebase_analytics: ^10.8.0

  # Google Sign-In
  google_sign_in: ^6.2.1

  # State Management
  flutter_riverpod: ^2.3.6

  # Offline Sync
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Other
  intl: ^0.20.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  fonts:
    - family: Comic Relief
      fonts:
        - asset: fonts/ComicRelief-Regular.ttf
        - asset: fonts/ComicRelief-Bold.ttf
          weight: 700