// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDItO4zmbvSm6pTa_KqVWDUtVse-ZSgc2A',
    appId: '1:592661765920:web:d2b06f30087eb7cd54c145',
    messagingSenderId: '592661765920',
    projectId: 'chkidsapp',
    authDomain: 'chkidsapp.firebaseapp.com',
    storageBucket: 'chkidsapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD31Pe201SPDTNlz9tlGN46W-ffTREZyuA',
    appId: '1:592661765920:android:d18ebde6427db17e54c145',
    messagingSenderId: '592661765920',
    projectId: 'chkidsapp',
    storageBucket: 'chkidsapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBPAqZQt19eFJwv-wXxh5kuIs_tuyrAKc',
    appId: '1:592661765920:ios:171b95360dd468b154c145',
    messagingSenderId: '592661765920',
    projectId: 'chkidsapp',
    storageBucket: 'chkidsapp.firebasestorage.app',
    iosBundleId: 'com.example.chKids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBPAqZQt19eFJwv-wXxh5kuIs_tuyrAKc',
    appId: '1:592661765920:ios:171b95360dd468b154c145',
    messagingSenderId: '592661765920',
    projectId: 'chkidsapp',
    storageBucket: 'chkidsapp.firebasestorage.app',
    iosBundleId: 'com.example.chKids',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDItO4zmbvSm6pTa_KqVWDUtVse-ZSgc2A',
    appId: '1:592661765920:web:7af574619c66ac4954c145',
    messagingSenderId: '592661765920',
    projectId: 'chkidsapp',
    authDomain: 'chkidsapp.firebaseapp.com',
    storageBucket: 'chkidsapp.firebasestorage.app',
  );
}